#ifndef SLOT_DEFS_H
#define SLOT_DEFS_H

#define NETWORK_TIME_SLOT 0
#define LAST_REF_FRAME_TIME_SLOT 1
#define NODE1_NUM_RECEIVED_FRAMES 2
#define NODE8_NUM_RECEIVED_FRAMES 3
#define NODE9_NUM_RECEIVED_FRAMES 4
#define NODE10_NUM_RECEIVED_FRAMES 5

#endif // SLOT_DEFS_H
