name: Generate Documentation

on:
  push:
    branches: [main]

jobs:

  docs:
    runs-on: ubuntu-22.04

    steps:
        - name: Setup SSH Key
          uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }} 

        - name: Clone Repo 
          uses: actions/checkout@v3
          with:
              submodules: 'recursive'

        - name: Generate Documentation
          uses: mattnotmitt/doxygen-action@v1.9.5
          with:
              working-directory: .
              doxyfile-path: ./Doxyfile

        - name: Pages Deployment
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./html
              force_orphan: true
